Prueba_Middleware/webapp/Models/DepartamentoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models
{
    public class DepartamentoViewModel
    {
        public int ID_DEPARTAMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}

Prueba_Middleware/webapp/Models/DepartamentosViewModel.cs
using SmartAdminMvc.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models
{
    public class DepartamentosViewModel
    {
        public int ID_DEPARTAMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public List<EMPLEADOS> EMPLEADOS { get; set; }
    }
}

Prueba_Middleware/webapp/Areas/Landing/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Areas.Landing.Controllers
{
    public class LandingController : Controller
    {
        //
        // GET: /Landing/Index
        public ActionResult Index()
        {
            return View();
        }
	}
}

Prueba_Middleware/webapp/Controllers/DepartamentosController.cs
using Newtonsoft.Json;
using SmartAdminMvc.Clases;
using SmartAdminMvc.Database;
using SmartAdminMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Controllers
{
    public class DepartamentosController : Controller
    {
        private PruebaAdmisionEntities db;
        private string URI = "https://localhost:44392/";
        private static readonly HttpClient client = new HttpClient();

        public DepartamentosController()
        {
            db = new PruebaAdmisionEntities();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

        // GET: Departamentos
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetDepartamentos()
        {
            try
            {
                client.DefaultRequestHeaders.Clear();

                var response = await client.GetAsync(URI + "api/Departamentos");

                if (response.StatusCode == HttpStatusCode.OK)
                {
                    string result = await response.Content.ReadAsStringAsync();
                    var departamentoslist = JsonConvert.DeserializeObject<List<DepartamentoViewModel>>(result);

                    return Json(new { data = departamentoslist }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new ResponseResult { Result = false, Message = response.StatusCode.ToString() });
                }
            }
            catch (Exception e)
            {
                return Json(new ResponseResult { Result = false, Message = e.ToString() });
            }
        }

        public PartialViewResult FormDepartamento()
        {
            return PartialView();
        }

        public async Task<JsonResult> Save(DepartamentosViewModel departamento)
        {
            string content = JsonConvert.SerializeObject(departamento);
            HttpContent httpContent = new StringContent(content, Encoding.UTF8, "application/json");

            var responseCreationFields = await client.PostAsync(URI + "api/Departamentos", httpContent);
            if (responseCreationFields.StatusCode == HttpStatusCode.OK)
            {
                string result = await responseCreationFields.Content.ReadAsStringAsync();
                var response = JsonConvert.DeserializeObject<ResponseResult>(result);

                return Json(new { data = response }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new ResponseResult { Result = false, Message = responseCreationFields.StatusCode.ToString() });
            }
        }
    }
}

Prueba_Middleware/webapp/Areas/Landing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SmartAdmin Landing</title>

    <!-- #Bootstrap Core CSS -->
    <link type="text/css" href="~/areas/landing/content/css/bootstrap.min.css" rel="stylesheet">

    <!-- #SLIDER REVOLUTION 4.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="~/areas/landing/content/css/extralayers.css" media="screen">
    <link rel="stylesheet" type="text/css" href="~/areas/landing/content/css/settings.css" media="screen">

    <!-- #RELATED CSS -->
    <link type="text/css" href="~/areas/landing/content/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link type="text/css" href="~/areas/landing/content/css/nivo-lightbox.css" rel="stylesheet">
    <link type="text/css" href="~/areas/landing/content/css/nivo-lightbox-theme/default/default.css" rel="stylesheet">
    <link type="text/css" href="~/areas/landing/content/css/animate.css" rel="stylesheet">

    <!-- #SMARTADMIN LANDING CSS -->
    <link type="text/css" href="~/areas/landing/content/css/main.css" rel="stylesheet">
    <link type="text/css" href="~/areas/landing/content/color/default.css" rel="stylesheet">

    <!-- #FAVICONS -->
    <link rel="shortcut icon" href="~/areas/landing/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/areas/landing/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- #GOOGLE FONT -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

</head>

<!--

TABLE OF CONTENTS.

Use search to find needed section.

===================================================================

|  01. #MENU                                                      |
|  02. #INTRO                                                     |
|  03. #PRICING                                                   |
|  04. #TEAM                                                      |
|  05. #FEATURES                                                  |
|  06. #SCREENSHOT                                                |
|  07. #UPDATES                                                   |
|  08. #QUOTES                                                    |
|  09. #CONTACT                                                   |
|  10. #BOTTOM CONTENT                                            |
|  11. #FOOTER                                                    |
|  12. #Core Javascript                                           |
|  13. #REVOLUITION SLIDER                                        |
|  14. #PAGE SCRIPT                                               |

===================================================================

-->

<body data-spy="scroll">

    <div class="container">

        <!-- Section: #MENU -->
        <ul id="gn-menu" class="gn-menu-main">
            <li class="gn-trigger">
                <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
                <nav class="gn-menu-wrapper">
                    <div class="gn-scroller">
                        <ul class="gn-menu">
                            <li class="gn-search-item">
                                <input placeholder="Search" type="search" class="gn-search">
                                <a class="gn-icon gn-icon-search"><span>Search</span></a>
                            </li>
                            <li>
                                <a href="#pricing" class="gn-icon gn-icon-download">Pricing</a>
                            </li>
                            <li>
                                <a href="#team" class="gn-icon gn-icon-article">Team</a>
                            </li>
                            <li>
                                <a href="#features" class="gn-icon gn-icon-help">Features</a>
                            </li>
                            <li>
                                <a href="#screenshots" class="gn-icon gn-icon-pictures">Screenshots</a>
                            </li>
                            <li>
                                <a href="#updates" class="gn-icon gn-icon-cog">Updates</a>
                            </li>
                            <li>
                                <a href="#contact" class="gn-icon gn-icon-archive">Contact</a>
                            </li>
                        </ul>
                    </div><!-- /gn-scroller -->
                </nav>
            </li>
            <li class="hidden-xs">
                <a href="/landing/landing"><img src="/areas/landing/content/img/logo.png" style="width: 135px; margin-top: -4px;" /></a>
            </li>
            <li>
                <ul class="company-social">
                    <li class="social-facebook">
                        <a href="javascript:void(0);" target="_blank"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li class="social-twitter">
                        <a href="javascript:void(0);" target="_blank"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li class="social-dribble">
                        <a href="javascript:void(0);" target="_blank"><i class="fa fa-dribbble"></i></a>
                    </li>
                    <li class="social-google">
                        <a href="javascript:void(0);" target="_blank"><i class="fa fa-google-plus"></i></a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- Section: #MENU -->

    </div>

    @RenderBody()

    <!-- #FOOTER -->
    <footer>

        <div class="footer-content clearfix">
            <div class="container custom-container">
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <a href="#" class="footer-logo">About Us</a>
                        <p>
                            Fusce gravida tortor felis, ac dictum risus sagittis id.
                        </p>
                        <p>
                            Donec volutpat, mi vel egestas eleifend, dolor arcu iaculis nunc. Fusce gravida tortor felis, ac dictum risus sagittis id. Morbi posuere justo eleifend libero ultricies ultrices.
                        </p>
                        <a href="#" class="learn-more">learn more</a>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <h3>Recent Tweets</h3>
                        <div class="recent-post clearfix">
                            <div class="footer-thumb-img">
                                <span class="footer-overlay-img"></span>
                            </div>
                            <p>
                                Fusce gravida tortor felis, ac dictum risus sagittis
                                <span class="date">November 15, 2014</span>
                            </p>

                        </div>
                        <div class="recent-post clearfix">
                            <div class="footer-thumb-img">
                                <span class="footer-overlay-img"></span>
                            </div>
                            <p>
                                Fusce gravida tortor felis, ac dictum risus sagittis
                                <span class="date">November 11, 2014</span>
                            </p>

                        </div>
                        <div class="recent-post clearfix">
                            <div class="footer-thumb-img">
                                <span class="footer-overlay-img"></span>
                            </div>
                            <p>
                                Fusce gravida tortor felis, ac dictum risus sagittis
                                <span class="date">November 10, 2014</span>
                            </p>

                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <h3>Top Tags</h3>
                        <div class="footer-tags">
                            <ul>
                                <li>
                                    <a href="#">Web Design</a>
                                </li>
                                <li>
                                    <a href="#">Services</a>
                                </li>
                                <li>
                                    <a href="#">Landing</a>
                                </li>
                                <li>
                                    <a href="#">SmartAdmin</a>
                                </li>
                                <li>
                                    <a href="#">.Net</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <h3>Flicker photos (recent)</h3>
                        <div class="flicker-widget">
                            <a href="#"></a>
                            <a href="#"></a>
                            <a href="#"></a>
                            <a href="#"></a>
                            <a href="#"></a>
                            <a href="#"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                        <p>
                            Copyright © 2015 - Your Company Name
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- / #FOOTER -->
    <!-- # Core JavaScript Files -->
    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script>
        if (!window.jQuery) {
            document.write('<script src="/landing/landing/content/js/libs/jquery-2.0.2.min.js"><\/script>');
        }
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script>
        if (!window.jQuery.ui) {
            document.write('<script src="/landing/landing/content/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
        }
    </script>


    <!-- BOOTSTRAP JS -->
    <script src="/areas/landing/content/js/bootstrap/bootstrap.min.js"></script>

    <!--# JS PLUGINS -->
    <script src="/areas/landing/content/js/plugins/classie.js"></script>
    <script src="/areas/landing/content/js/plugins/gnmenu.js"></script>
    <script src="/areas/landing/content/js/plugins/jquery.scrollUp.js"></script>
    <script src="/areas/landing/content/js/plugins/nivo-lightbox.min.js"></script>
    <script src="/areas/landing/content/js/plugins/smoothscroll.js"></script>
    <script src="/areas/landing/content/js/plugins/jquery.themepunch.plugins.min.js"></script>
    <script src="/areas/landing/content/js/plugins/jquery.themepunch.revolution.min.js"></script>

    <!-- # Custom Theme JavaScript -->
    <script src="/areas/landing/content/js/custom.js"></script>

    <!-- #PAGE SCRIPT -->
    <script type="text/javascript">
        jQuery(document).ready(function () {

            jQuery('.tp-banner').show().revolution({
                dottedOverlay: "none",
                delay: 8000,
                startwidth: 1170,
                startheight: 700,
                hideThumbs: 200,

                thumbWidth: 100,
                thumbHeight: 50,
                thumbAmount: 5,

                navigationType: "bullet",
                navigationArrows: "solo",
                navigationStyle: "preview4",

                touchenabled: "on",
                onHoverStop: "off",

                swipe_velocity: 0.7,
                swipe_min_touches: 1,
                swipe_max_touches: 1,
                drag_block_vertical: false,

                parallax: "mouse",
                parallaxBgFreeze: "on",
                parallaxLevels: [7, 4, 3, 2, 5, 4, 3, 2, 1, 0],

                keyboardNavigation: "off",

                navigationHAlign: "center",
                navigationVAlign: "bottom",
                navigationHOffset: 0,
                navigationVOffset: 20,

                soloArrowLeftHalign: "left",
                soloArrowLeftValign: "center",
                soloArrowLeftHOffset: 20,
                soloArrowLeftVOffset: 0,

                soloArrowRightHalign: "right",
                soloArrowRightValign: "center",
                soloArrowRightHOffset: 20,
                soloArrowRightVOffset: 0,

                shadow: 0,
                fullWidth: "off",
                fullScreen: "on",

                spinner: "spinner4",

                stopLoop: "off",
                stopAfterLoops: -1,
                stopAtSlide: -1,

                shuffle: "off",

                autoHeight: "off",
                forceFullWidth: "off",

                hideThumbsOnMobile: "off",
                hideNavDelayOnMobile: 1500,
                hideBulletsOnMobile: "off",
                hideArrowsOnMobile: "off",
                hideThumbsUnderResolution: 0,

                hideSliderAtLimit: 0,
                hideCaptionAtLimit: 0,
                hideAllCaptionAtLilmit: 0,
                startWithSlide: 0,
                fullScreenOffsetContainer: ""
            });

        });
        //ready

        $.scrollUp();
    </script>

</body>

</html>

Prueba_Middleware/webapp/Views/Departamentos/FormDepartamento.cshtml
@model SmartAdminMvc.Database.DEPARTAMENTOS

<style>
    .my-error-class {
        color: #FF0000; /* red */
    }

    .my-valid-class {
        color: green; /* green */
    }

    .error {
        margin-left: 12px;
    }
</style>

@{
    ViewBag.Title = "Cliente";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        &times;
    </button>
    <h4 class="modal-title">
        <i class="fa fa-plus"></i>
        &nbsp; Agregar Nuevo Departamento
    </h4>
</div>
<div class="modal-body" style="overflow-y:auto;height:480px;">
    <form id="FormDepartamento">
        @Html.HiddenFor(m => m.ID_DEPARTAMENTO)
        <div class="row">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.NOMBRE, "Nombre")
                @Html.EditorFor(m => m.NOMBRE, new { htmlAttributes = new { @class = "form-control", @style = "text-transform: uppercase", autofocus = "autofocus" } })
            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.REFERENCIA, "Referencia")
                @Html.TextBoxFor(m => m.REFERENCIA, new { @class = "form-control" , maxlength = "10"})
            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.DESCRIPCION, "Descripción")
                @Html.TextAreaFor(m => m.DESCRIPCION, new { @class = "form-control ", @style = "resize: none; WIDTH: 100%; HEIGHT: 50px; text-transform: uppercase;" })
            </div>
        </div>
        <button class="btn btn-success" onclick="AddEmpleado()" type="button">Agregar Empleado</button>
        <table id="tableEmpleados" class="table table-striped table-bordered" width="100%">
            <thead>
                <tr>
                    <th>Item</th>
                    <th data-hide="phone">Nombre</th>
                    <th data-class="expand">Descripcion</th>
                    <th data-class="expand">Género</th>
                    <th data-class="expand">Fecha Nacimiento</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>


    </form>
</div>
<div class="modal-footer">
    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="glyphicon glyphicon-remove"></i>&nbsp;Cancelar</button>
    <button type='button' class="btn btn-success" onclick="GuardarDepartamento()"><i class="glyphicon glyphicon-floppy-saved"></i>&nbsp;Guardar</button>
</div>

    <script>

    document.getElementById('NOMBRE').focus();

    $('.select2').select2({ width: '100%' });

    var formDepartamento = $("#FormDepartamento");

    var tableEmpleados = $("#tableEmpleados").DataTable({
        "dom": '',
        "columnDefs": [
            {
                "searchable": false
            },
        ]

    });

    formDepartamento.validate({
        ignore: [],
        rules: {
            NOMBRE: {
                required: true,
                maxlength: 100
            },
            REFERENCIA: {
                required: true,
            },
            DESCRIPCION: {
                required: true,
            },
        },
        messages: {
            NOMBRE: {
                required: "*Debe escribir el nombre del departamento.",
                maxlength: jQuery.format("Ingrese máximo {0} caracteres. ")
            },
            REFERENCIA: {
                required: "*Debe escribir la referencia.",
            },
            DESCRIPCION: {
                required: "*Debe escribir la descripción.",
            },
        },
        errorClass: "my-error-class",
        validClass: "my-valid-class",
        errorPlacement: function (error, element) {
            if (element.hasClass('select2') && element.next('.select2-container').length) {
                error.insertAfter(element.next('.select2-container'));
            } else {
                error.insertAfter(element);
            }
        }
    });

        function GuardarDepartamento() {
            var empleados = [];
            $('#tableEmpleados').DataTable().rows().every(function (rowIdx, tableLoop, rowLoop) {
                var data = this.data();
                var row = data[0];
            var item = {
                NOMBRE: $("#nombre" + row).val(),
                DESCRIPCION: $("#descripcion" + row).val(),
                GENERO_SEXO: $("#genero" + row).val(),
                FECHA_NACIMIENTO: $("#fecha" + row).val(),
            };
            empleados.push(item);
            })

            var model = {
                NOMBRE: $("#NOMBRE").val(),
                REFERENCIA: $("#REFERENCIA").val(),
                DESCRIPCION: $("#DESCRIPCION").val(),
                EMPLEADOS: empleados
            }

            console.log(model);
        if (formDepartamento.valid()) {

            $.ajax({
                url: '@Url.Action("Save", "Departamentos")',
                type: "POST",
                dataType: "JSON",
                beforeSend: function () {
                    LoadWaitNotification();
                },
                complete: function () {
                    UnloadWaitNotification();
                },
                data: model,
                success:
                    function (data) {
                        var success = data.data.Result;
                        var message = data.data.Message;
                        if (success == true) {
                            SuccessMessage(message);
                            $("#modalNuevoDepartamento").modal('hide');
                            AjaxReloadTable('@Url.Action("GetDepartamentos", "Departamentos")', $('#tableDepartamentos'));
                        }
                        else {
                            FailureMessage(message);
                        }
                    },
                error: function (data) {
                    FailureMessage("Error al intentar guardar el registro.");
                }
            });
            }
    }

    var valor = 1;

    function AddEmpleado() {
        tableEmpleados.row.add([
            valor,
            `<input type="text" id="nombre${valor}" class="form-control" required/>`,
            `<input type="text" id="descripcion${valor}" class="form-control" required/>`,
            `<input type="text" onchange="ChangeGenero(${valor},this.value)" id="genero${valor}" class="form-control" maxlength="1" required/>`,
            `<input type="date" id="fecha${valor}" class="form-control" required/>`,
            `<button id="del" type="button" class="btn btn-danger"><i class="fa fa-trash"></i></button>`
        ]).draw(false);
        valor = valor + 1;
        };

        $('#tableEmpleados tbody').on('click', '#del', function () {
            tableEmpleados
            .row($(this).parents('tr'))
            .remove()
                .draw();
        });

        function ChangeGenero(id, text) {
            if (text.toUpperCase() === "M" || text.toUpperCase() === "F") {
            }
            else {
                $("#genero" + id).val("")
                alert("Debe escribir M para Masculino, F para femenino")
            }
        }

    </script>

Prueba_Middleware/webapp/Views/Shared/_CurrentUser.cshtml
<div class="login-info">
    <span>
        <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            @*<img src="~/content/img/avatars/sunny.png" alt="me" class="online" />*@

            <span><i class="fa fa-user fa-lg"></i>&nbsp; @User.Identity.Name</span>
            @*<i class="fa fa-angle-down"></i>*@
        </a>
    </span>
</div>

Prueba_Middleware/webapp/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">SmartAdmin 1.8.0 <span class="hidden-xs"> - Web Application Framework</span> © 2011-2016</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                <div class="btn-group dropup">
                    <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

Prueba_Middleware/webapp/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<style>
    #logo img {
    width: 35%;
    height: 90%;
}
</style>

<header id="header">
    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"> <img src="~/content/img/logo-casajaar-navbar.png"> </span>

    </div>
    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->

Prueba_Middleware/webapp/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">

    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! Esta opción reiniciará todas las configuraciones de los widgets." data-html="true">
			<i class="fa fa-refresh"></i>
		</span>
    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Inicio</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

</div>
<!-- END RIBBON -->